name: Scrape FX Competitors
on:
  schedule:
    - cron: "*/1 * * * *"   # every 1 minutes (UTC)
  workflow_dispatch:

jobs:
  scrape:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Install Playwright
        run: |
          npm ci || npm install
          npx playwright install --with-deps chromium
      - name: Run scraper
        env:
          SHEET_ID: ${{ secrets.SHEET_ID }}
          GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}
          SHEET_NAME: ${{ secrets.SHEET_NAME }}
          LOG_SHEET_TITLE: ${{ secrets.LOG_SHEET_TITLE }}
        run: npm start
