name: Scrape FX Competitors

on:
  # Every 15 minutes (UTC)
  schedule:
    - cron: '*/15 * * * *'
  # Allow manual runs
  workflow_dispatch: {}

permissions:
  contents: read

# Avoid overlapping runs
concurrency:
  group: scrape-fx
  cancel-in-progress: false

jobs:
  scrape:
    runs-on: ubuntu-latest
    env:
      TZ: Asia/Seoul

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: |
          if [ -f package-lock.json ]; then
            npm ci
          else
            npm install
          fi

      - name: Install Playwright Chromium
        run: |
          npx playwright install --with-deps chromium

      - name: Show trigger (debug)
        run: |
          echo "Event=${{ github.event_name }}"
          echo "Run ID=${{ github.run_id }}"
          date -u

      - name: Run scraper
        env:
          SHEET_ID: ${{ secrets.SHEET_ID }}
          GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}
          # Optional custom tab names; safe to leave blank
          SHEET_VND: ${{ secrets.SHEET_VND }}
          SHEET_CNY: ${{ secrets.SHEET_CNY }}
          SHEET_NPR: ${{ secrets.SHEET_NPR }}
          SHEET_KHR: ${{ secrets.SHEET_KHR }}
        run: npm start

      - name: Upload debug artifacts (if any)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: debug
          path: debug/
          if-no-files-found: ignore
