name: Scrape FX Competitors

on:
  schedule:
    - cron: "*/15 * * * *"   # every 15 minutes (UTC)
  workflow_dispatch:

jobs:
  scrape:
    runs-on: ubuntu-latest
    env:
      TZ: Asia/Seoul
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install Playwright Chromium
        run: |
          npm ci || npm install
          npx playwright install --with-deps chromium

      - name: Show trigger
        run: echo "Event: ${{ github.event_name }} | started_at=${{ github.run_started_at }}"

      - name: Run scraper
        env:
          SHEET_ID: ${{ secrets.SHEET_ID }}
          GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}
          SHEET_VND: ${{ secrets.SHEET_VND }}
          SHEET_CNY: ${{ secrets.SHEET_CNY }}
          SHEET_NPR: ${{ secrets.SHEET_NPR }}
          SHEET_KHR: ${{ secrets.SHEET_KHR }}
        run: npm start
