name: Scrape FX Competitors
on:
  workflow_dispatch:
  schedule:
    - cron: "*/15 * * * *"   # every 15 minutes (UTC)

jobs:
  scrape:
    runs-on: ubuntu-latest
    env:
      TZ: Asia/Seoul
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Install Playwright
        run: |
          npm ci || npm install
          npx playwright install --with-deps chromium
      - name: Run scraper
        env:
          SHEET_ID: ${{ secrets.SHEET_ID }}
          GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}
          # Optional:
          # TIMEZONE: ${{ secrets.TIMEZONE }}          # default Asia/Seoul
          # SHEET_E9PAY: ${{ secrets.SHEET_E9PAY }}    # default "e9pay"
          # SHEET_GMONEY: ${{ secrets.SHEET_GMONEY }}  # default "gmoney"
          # SHEET_GME: ${{ secrets.SHEET_GME }}        # default "gme"
        run: npm start
