name: Scrape FX Competitors

on:
  schedule:
    - cron: "*/15 * * * *"   # every 15 minutes (UTC)
  workflow_dispatch:

jobs:
  scrape:
    runs-on: ubuntu-latest
    env:
      TZ: Asia/Seoul
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install Playwright Chromium
        run: |
          npm ci || npm install
          npx playwright install --with-deps chromium

      - name: Show trigger
        shell: bash
        run: |
          echo "Event: $GITHUB_EVENT_NAME"
          echo "Run ID: $GITHUB_RUN_ID"
          echo "Run number: $GITHUB_RUN_NUMBER"
          date -u

           - name: Run scraper
        env:
          # Ensure unhandled rejections fail the job
          NODE_OPTIONS: --unhandled-rejections=strict

          # From GitHub Secrets
          SHEET_ID: ${{ secrets.SHEET_ID }}
          GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}

          # Tab names (choose ONE approach)
          # A) from secrets:
          SHEET_VND: ${{ secrets.SHEET_VND }}
          SHEET_CNY: ${{ secrets.SHEET_CNY }}
          SHEET_NPR: ${{ secrets.SHEET_NPR }}
          SHEET_KHR: ${{ secrets.SHEET_KHR }}
          # B) or hard-code (uncomment these and remove A):
          # SHEET_VND: VND
          # SHEET_CNY: CNY
          # SHEET_NPR: NPR
          # SHEET_KHR: KHR
        run: npm start
