name: Scrape FX Competitors

on:
  workflow_dispatch:
  schedule:
    - cron: "*/15 * * * *"   # every 15 minutes (UTC)

jobs:
  scrape:
    runs-on: ubuntu-latest
    env:
      TZ: Asia/Seoul
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install Playwright + Chromium
        run: |
          npm install
          npx playwright install --with-deps chromium

      - name: Run scraper
        env:
          SHEET_ID: ${{ secrets.SHEET_ID }}
          GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}
        run: npm start
