name: Scrape FX Competitors
on:
  workflow_dispatch:
  schedule:
    - cron: "*/1 * * * *"   # TEMP: every 1 minute (UTC)

jobs:
  scrape:
    runs-on: ubuntu-latest
    env:
      TZ: Asia/Seoul          # <-- change to your timezone if you want
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Install Playwright
        run: |
          npm ci || npm install
          npx playwright install --with-deps chromium
      - name: Run scraper
        env:
          SHEET_ID: ${{ secrets.SHEET_ID }}
          GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}
          SHEET_NAME: ${{ secrets.SHEET_NAME }}
          LOG_SHEET_TITLE: ${{ secrets.LOG_SHEET_TITLE }}
        run: npm start
